"""Hand-written concept questions for the pop quiz: the ideas a management interview or a first job assumes.

(field slug, level 1-3, question, right answer, three wrong answers, one-line explanation).
Only well-established textbook facts go in here. The field slugs match the fields in the taxonomy, so the
quiz can lean towards the fields a player follows.
"""

CONCEPTS: list[tuple[str, int, str, str, tuple[str, str, str], str]] = [
    # Marketing
    ("marketing", 1, "In the classic marketing mix, what are the four Ps?", "Product, price, place, promotion",
     ("Product, people, process, profit", "Planning, pricing, packaging, publicity", "Positioning, packaging, placement, pricing"),
     "The four Ps are the levers a marketer controls: what you sell, what it costs, where it is sold and how it is promoted."),
    ("marketing", 1, "STP in marketing stands for what?", "Segmentation, targeting, positioning",
     ("Strategy, tactics, planning", "Sales, trade, promotion", "Survey, test, pilot"),
     "You split the market into segments, choose which to serve, then decide how to position the brand for them."),
    ("marketing", 1, "What do the letters in AIDA stand for?", "Attention, interest, desire, action",
     ("Awareness, interest, decision, advocacy", "Attention, insight, demand, acquisition", "Audience, impact, design, action"),
     "AIDA is a model of the steps a buyer moves through, from noticing an ad to acting on it."),
    ("marketing", 2, "Net Promoter Score asks customers how likely they are to recommend you, on a scale of what?", "0 to 10",
     ("1 to 5", "1 to 7", "1 to 100"),
     "Scores of 9 and 10 are promoters, 7 and 8 are passives, and 0 to 6 are detractors."),
    ("marketing", 2, "Customer acquisition cost (CAC) is what?", "The total cost of winning one new customer",
     ("The price a customer pays for the first order", "The cost of keeping an existing customer", "The discount given at sign-up"),
     "CAC adds up marketing and sales spend and divides it by the customers won in the same period."),
    ("marketing", 3, "Which pricing approach sets the price by what customers are willing to pay, not by cost?", "Value-based pricing",
     ("Cost-plus pricing", "Penetration pricing", "Loss-leader pricing"),
     "Cost-plus starts from your costs. Value-based pricing starts from the worth the customer sees."),
    # Finance
    ("finance", 1, "What does EBITDA stand for?", "Earnings before interest, taxes, depreciation and amortisation",
     ("Earnings before investment, tax, debt and assets", "Equity before interest, taxes, dividends and amortisation", "Earnings after interest, taxes, depreciation and assets"),
     "EBITDA is a rough measure of operating profit before financing and accounting charges."),
    ("finance", 1, "Which statement shows assets, liabilities and equity at one point in time?", "The balance sheet",
     ("The income statement", "The cash flow statement", "The budget"),
     "The balance sheet is a snapshot. The income statement and cash flow statement cover a period."),
    ("finance", 1, "The break-even point is where what happens?", "Total revenue equals total cost",
     ("Profit is at its highest", "Fixed costs fall to zero", "Sales equal last year's sales"),
     "Below break-even the business loses money. Above it, each extra sale adds to profit."),
    ("finance", 2, "The price-to-earnings (P/E) ratio compares a share price with what?", "Earnings per share",
     ("Book value per share", "Dividend per share", "Revenue per employee"),
     "P/E shows how much investors pay for each rupee or dollar of a company's earnings."),
    ("finance", 2, "Working capital is what?", "Current assets minus current liabilities",
     ("Total assets minus total liabilities", "Cash plus long-term investments", "Revenue minus operating costs"),
     "It measures whether a company can cover its short-term obligations."),
    ("finance", 2, "CAGR measures what?", "The smoothed yearly growth rate over a period",
     ("The highest growth in any single year", "Growth in the most recent quarter", "The average of the yearly percentages"),
     "CAGR is the constant yearly rate that would take you from the start value to the end value."),
    ("finance", 2, "Gross margin is calculated as what?", "(Revenue minus cost of goods sold) divided by revenue",
     ("Net profit divided by revenue", "Operating profit divided by assets", "Revenue divided by cost of goods sold"),
     "Gross margin shows how much of each sale is left after the direct cost of making or buying the product."),
    ("finance", 3, "A project has a positive net present value. What does that mean?", "It is expected to earn more than the required return",
     ("It will pay back within a year", "It carries no risk", "Its cash flows are all positive"),
     "NPV discounts future cash flows at the required return. Above zero means the project adds value."),
    ("finance", 3, "WACC is best described as what?", "The blended cost of a company's debt and equity",
     ("The average cost of goods sold", "The weekly average cash cycle", "The cost of a single loan"),
     "WACC is often the discount rate used when valuing a company's cash flows."),
    # Strategy and consulting
    ("consulting", 1, "How many forces are in Porter's model of industry competition?", "Five",
     ("Three", "Four", "Seven"),
     "Rivalry, new entrants, substitutes, buyer power and supplier power."),
    ("consulting", 1, "What does SWOT stand for?", "Strengths, weaknesses, opportunities, threats",
     ("Strategy, work, operations, targets", "Sales, wins, orders, turnover", "Strengths, wins, options, tactics"),
     "Strengths and weaknesses are internal. Opportunities and threats are external."),
    ("consulting", 2, "In a BCG growth-share matrix, a business with high share in a slow-growing market is called what?", "A cash cow",
     ("A star", "A question mark", "A dog"),
     "Cash cows earn steady cash with little need to invest in growth."),
    ("consulting", 2, "In consulting, MECE means a set of answers should be what?", "Mutually exclusive and collectively exhaustive",
     ("Measured, evidenced, clear and efficient", "Meaningful, exact, concise and early", "Managed, executed, controlled and evaluated"),
     "No overlaps and no gaps. It keeps a structure clean and complete."),
    ("consulting", 2, "The Ansoff matrix compares growth options across which two things?", "Products and markets, each existing or new",
     ("Price and quality", "Cost and revenue", "Size and speed"),
     "It gives four routes: market penetration, market development, product development and diversification."),
    ("consulting", 2, "In a market-sizing case, what does 'top-down' mean?", "Start from a large total and narrow it down",
     ("Start from one customer and multiply up", "Start from the competitor's sales", "Start from the price and work backwards"),
     "Bottom-up does the opposite: it builds up from units such as households or stores."),
    ("consulting", 3, "Who wrote The Pyramid Principle, a staple of consulting communication?", "Barbara Minto",
     ("Michael Porter", "Clayton Christensen", "Peter Drucker"),
     "Minto's rule: lead with the answer, then support it with grouped arguments."),
    ("consulting", 3, "Blue Ocean Strategy is about what?", "Creating uncontested market space instead of fighting head-on",
     ("Cutting prices to win share", "Entering the largest existing market", "Copying the market leader faster"),
     "Kim and Mauborgne argue for making the competition irrelevant rather than beating it."),
    ("consulting", 3, "Which author is best known for the theory of disruptive innovation?", "Clayton Christensen",
     ("Michael Porter", "Peter Drucker", "Philip Kotler"),
     "Christensen described how simpler, cheaper entrants can overtake incumbents from below."),
    ("consulting", 3, "A hypothesis-driven approach to a case starts with what?", "An early answer that you then try to prove or disprove",
     ("A full list of every possible cause", "The client's financial statements", "A survey of the market"),
     "It saves time: you test the most likely answer first instead of gathering everything."),
    # Operations
    ("operations", 1, "Just-in-time inventory aims to do what?", "Receive goods only when they are needed",
     ("Hold as much stock as possible", "Buy in the largest batches", "Ship everything by air"),
     "It cuts the cost of holding stock but depends on reliable suppliers."),
    ("operations", 2, "What does DMAIC stand for in Six Sigma?", "Define, measure, analyze, improve, control",
     ("Design, manage, audit, implement, check", "Decide, model, adjust, integrate, confirm", "Define, monitor, align, iterate, close"),
     "DMAIC is the five-step method for improving an existing process."),
    ("operations", 2, "Kanban manages work by using what?", "Visual signals or cards that pull work forward",
     ("A fixed yearly plan", "Daily performance reviews", "A single shared spreadsheet"),
     "Work is pulled when there is capacity, which limits work in progress."),
    ("operations", 2, "EOQ stands for what?", "Economic order quantity",
     ("Estimated output quota", "Extra order queue", "Effective operating quality"),
     "It is the order size that minimises ordering and holding costs together."),
    ("operations", 3, "What is the bullwhip effect in a supply chain?", "Small changes in retail demand grow into large swings upstream",
     ("Suppliers delivering late in bad weather", "Prices rising as volume falls", "Stock moving in a fixed loop"),
     "Each step in the chain over-corrects, so orders get more volatile the further you are from the customer."),
    # HR
    ("hr", 1, "What does OKR stand for?", "Objectives and key results",
     ("Operations and key revenue", "Outcomes, knowledge and reviews", "Objectives, KPIs and roles"),
     "An objective says where you want to go. Key results measure whether you got there."),
    ("hr", 1, "A 360-degree review collects feedback from whom?", "Managers, peers, direct reports and sometimes customers",
     ("Only the employee's manager", "Only the employee", "Only human resources"),
     "The idea is a rounded view from everyone who works with the person."),
    ("hr", 1, "Attrition rate is what?", "The share of employees who leave in a period",
     ("The share of new hires who are promoted", "The number of open roles", "The average time to hire"),
     "It is usually reported per year or per quarter."),
    ("hr", 2, "In Tuckman's model of team development, which stage comes right after forming?", "Storming",
     ("Norming", "Performing", "Adjourning"),
     "The stages are forming, storming, norming and performing, with adjourning added later."),
    ("hr", 3, "Herzberg's two-factor theory calls pay and working conditions what?", "Hygiene factors",
     ("Motivators", "Growth needs", "Esteem needs"),
     "Hygiene factors prevent unhappiness but do not by themselves motivate. Achievement and recognition do."),
    ("hr", 3, "What is the first step in Kotter's eight-step change model?", "Create a sense of urgency",
     ("Build a guiding coalition", "Communicate the vision", "Celebrate short-term wins"),
     "People rarely change until they see why staying put is risky."),
    ("hr", 3, "In the ADKAR change model, what does the first letter stand for?", "Awareness of the need for change",
     ("Agreement on the plan", "Authority to decide", "Assessment of skills"),
     "ADKAR runs awareness, desire, knowledge, ability and reinforcement."),
    # Technology and digital transformation
    ("digital-transformation", 1, "IaaS, PaaS and SaaS are models of what?", "Cloud computing",
     ("Data storage formats", "Project management", "Cyber insurance"),
     "They differ in how much the provider manages: infrastructure, platform or the whole application."),
    ("digital-transformation", 1, "What does robotic process automation (RPA) do?", "Uses software robots to do repetitive digital tasks",
     ("Builds physical robots for factories", "Replaces a company's servers", "Writes marketing copy"),
     "RPA tools click, copy and paste through systems the way a person would."),
    ("digital-transformation", 1, "What does an API let one piece of software do?", "Talk to another in an agreed way",
     ("Store data permanently", "Encrypt a message", "Design a web page"),
     "APIs are the contracts that let separate systems work together."),
    ("digital-transformation", 2, "What is a minimum viable product?", "The simplest version that lets you learn from real users",
     ("A product with every planned feature", "A prototype shown only to investors", "The cheapest product on the market"),
     "The MVP idea comes from the lean startup approach: learn early, before building everything."),
    ("digital-transformation", 2, "In agile, what is a sprint?", "A short fixed period in which a team completes a set of work",
     ("A meeting to plan the year", "The final release of a product", "A review of team performance"),
     "Sprints are commonly one to four weeks long."),
    ("digital-transformation", 3, "Zero trust security assumes what?", "No user or device is trusted by default",
     ("Everything inside the office network is safe", "Passwords are enough", "Only outsiders are a risk"),
     "Every request is checked, whether it comes from inside or outside the network."),
    ("platform-business", 1, "The network effect means a product becomes more valuable when what happens?", "More people use it",
     ("It gets cheaper to make", "It gets more features", "It is sold in more countries"),
     "Phones, marketplaces and social networks all work this way."),
    ("platform-business", 3, "In a two-sided platform, what is the chicken-and-egg problem?", "Each side needs the other to show up first",
     ("Prices must fall before demand rises", "Suppliers cannot agree on standards", "Users leave when fees rise"),
     "A marketplace needs sellers to attract buyers and buyers to attract sellers."),
    ("data-ai", 1, "What does A/B testing do?", "Compares two versions to see which performs better",
     ("Tests a product with only two users", "Measures the speed of a website", "Checks code for errors"),
     "Users are split at random so the difference in results can be put down to the change."),
    ("data-ai", 1, "SQL is mainly used to do what?", "Query and manage data in databases",
     ("Design user interfaces", "Send email at scale", "Build mobile apps"),
     "SQL stands for structured query language."),
    # General
    ("sales", 1, "What does CRM stand for?", "Customer relationship management",
     ("Customer revenue model", "Corporate resource planning", "Central retail management"),
     "A CRM system keeps a record of every customer conversation and deal."),
    ("sales", 1, "What is a KPI?", "A measurable value that shows progress towards a goal",
     ("A yearly performance appraisal", "A list of key products", "A type of financial statement"),
     "KPI stands for key performance indicator."),
]
