"""Official RSS/Atom feeds only. (name, feed_url, authority 1-5). Every URL here answered with a
valid feed when last probed; a source that later breaks is recorded, not fatal (see ingest)."""

SOURCES: list[tuple[str, str, int]] = [
    # Marketing, retail and customer experience
    ("Marketing Dive", "https://www.marketingdive.com/feeds/news/", 4),
    ("Marketing Week", "https://www.marketingweek.com/feed/", 4),
    ("Adweek", "https://www.adweek.com/feed/", 4),
    ("Google Ads & Commerce Blog", "https://blog.google/products/ads-commerce/rss/", 5),
    ("Social Media Examiner", "https://feeds.feedburner.com/SocialMediaExaminer", 3),
    ("Retail Dive", "https://www.retaildive.com/feeds/news/", 4),
    ("Customer Experience Dive", "https://www.customerexperiencedive.com/feeds/news/", 4),
    # India business and markets
    ("Mint - Companies", "https://www.livemint.com/rss/companies", 4),
    ("Mint - Markets", "https://www.livemint.com/rss/markets", 4),
    ("Mint - Economy", "https://www.livemint.com/rss/economy", 4),
    ("Economic Times - FMCG", "https://economictimes.indiatimes.com/industry/cons-products/fmcg/rssfeeds/13358259.cms", 4),
    ("Economic Times - Markets", "https://economictimes.indiatimes.com/markets/rssfeeds/1977021501.cms", 4),
    ("Economic Times - Tech", "https://economictimes.indiatimes.com/tech/rssfeeds/13357270.cms", 4),
    ("Economic Times - Jobs", "https://economictimes.indiatimes.com/jobs/rssfeeds/107115.cms", 3),
    ("BusinessLine - Companies", "https://www.thehindubusinessline.com/companies/feeder/default.rss", 4),
    ("BusinessLine - Markets", "https://www.thehindubusinessline.com/markets/feeder/default.rss", 4),
    ("RBI Press Releases", "https://www.rbi.org.in/pressreleases_rss.xml", 5),
    # Finance and banking
    ("CNBC - Finance", "https://www.cnbc.com/id/10000664/device/rss/rss.html", 4),
    ("CFO Dive", "https://www.cfodive.com/feeds/news/", 4),
    ("Banking Dive", "https://www.bankingdive.com/feeds/news/", 4),
    ("PYMNTS", "https://www.pymnts.com/feed/", 3),
    ("Finextra", "https://www.finextra.com/rss/headlines.aspx", 4),
    # Technology, engineering, data and AI
    ("Ars Technica", "https://feeds.arstechnica.com/arstechnica/index", 4),
    ("The Verge", "https://www.theverge.com/rss/index.xml", 3),
    ("TechCrunch", "https://techcrunch.com/feed/", 3),
    ("Wired", "https://www.wired.com/feed/rss", 3),
    ("ZDNet", "https://www.zdnet.com/news/rss.xml", 3),
    ("Computer Weekly", "https://www.computerweekly.com/rss/All-Computer-Weekly-content.xml", 4),
    ("InfoQ", "https://feed.infoq.com/", 4),
    ("GitHub Blog", "https://github.blog/feed/", 5),
    ("AWS News Blog", "https://aws.amazon.com/blogs/aws/feed/", 5),
    ("Google Cloud Blog", "https://cloudblog.withgoogle.com/rss/", 5),
    ("MIT Technology Review", "https://www.technologyreview.com/feed/", 5),
    ("OpenAI News", "https://openai.com/blog/rss.xml", 5),
    ("NVIDIA Blog", "https://blogs.nvidia.com/feed/", 4),
    ("KDnuggets", "https://www.kdnuggets.com/feed", 3),
    # Security
    ("Krebs on Security", "https://krebsonsecurity.com/feed/", 5),
    ("BleepingComputer", "https://www.bleepingcomputer.com/feed/", 4),
    ("The Hacker News", "https://thehackernews.com/feeds/posts/default", 4),
    # Operations and supply chain
    ("Supply Chain Dive", "https://www.supplychaindive.com/feeds/news/", 4),
    ("Manufacturing Dive", "https://www.manufacturingdive.com/feeds/news/", 4),
    ("FreightWaves", "https://www.freightwaves.com/news/feed", 4),
    # HR
    ("HR Dive", "https://www.hrdive.com/feeds/news/", 4),
    ("ETHRWorld", "https://hr.economictimes.indiatimes.com/rss/topstories", 3),
    # Consulting and strategy
    ("McKinsey Insights", "https://www.mckinsey.com/insights/rss", 5),
    # Healthcare
    ("Fierce Healthcare", "https://www.fiercehealthcare.com/rss/xml", 4),
    ("Healthcare Dive", "https://www.healthcaredive.com/feeds/news/", 4),
    ("STAT", "https://www.statnews.com/feed/", 5),
    ("MedCity News", "https://medcitynews.com/feed/", 3),
    ("Fierce Pharma", "https://www.fiercepharma.com/rss/xml", 4),
    # Construction, energy and manufacturing
    ("Construction Dive", "https://www.constructiondive.com/feeds/news/", 4),
    ("Utility Dive", "https://www.utilitydive.com/feeds/news/", 4),
    ("Waste Dive", "https://www.wastedive.com/feeds/news/", 3),
    # Education
    ("Education Dive", "https://www.educationdive.com/feeds/news/", 4),
    ("K-12 Dive", "https://www.k12dive.com/feeds/news/", 4),
    ("Higher Ed Dive", "https://www.highereddive.com/feeds/news/", 4),
    ("EdSurge", "https://www.edsurge.com/articles_rss", 3),
    # Law
    ("Above the Law", "https://abovethelaw.com/feed/", 3),
    # Hospitality and travel
    ("Skift", "https://skift.com/feed/", 4),
    ("Eater", "https://www.eater.com/rss/index.xml", 3),
    ("Restaurant Dive", "https://www.restaurantdive.com/feeds/news/", 4),
    # Media, entertainment and design
    ("Variety", "https://variety.com/feed/", 4),
    ("Deadline", "https://deadline.com/feed/", 4),
    ("The Hollywood Reporter", "https://www.hollywoodreporter.com/feed/", 4),
    ("Design Week", "https://www.designweek.co.uk/feed/", 3),
    ("Creative Bloq", "https://www.creativebloq.com/feeds.xml", 3),
    # Science and agriculture
    ("Nature", "https://www.nature.com/nature.rss", 5),
    ("ScienceDaily", "https://www.sciencedaily.com/rss/top/science.xml", 3),
    ("Phys.org", "https://phys.org/rss-feed/", 3),
    ("AgFunder News", "https://agfundernews.com/feed", 3),
    ("Mongabay", "https://news.mongabay.com/feed/", 3),
    ("Farm Progress", "https://www.farmprogress.com/rss.xml", 3),
    # Digital transformation, platforms and B2B
    ("CIO", "https://www.cio.com/feed/", 4),
    ("MIT Sloan Management Review", "https://sloanreview.mit.edu/feed/", 4),
    ("B2B Marketing", "https://www.b2bmarketing.net/feed", 3),
    ("Modern Retail", "https://www.modernretail.co/feed/", 3),
    # Business schools and management
    ("Poets&Quants", "https://poetsandquants.com/feed/", 3),
    ("Knowledge at Wharton", "https://knowledge.wharton.upenn.edu/feed/", 4),
    ("Ivey Business Journal", "https://iveybusinessjournal.com/feed/", 3),
    ("The Economist - Business", "https://www.economist.com/business/rss.xml", 4),
    ("Financial Times - Companies", "https://www.ft.com/companies?format=rss", 4),
    # Indian business, startups and brands
    ("Business Today", "https://www.businesstoday.in/rss/latest", 3),
    ("Fortune India", "https://www.fortuneindia.com/feed", 3),
    ("Economic Times - Industry", "https://economictimes.indiatimes.com/industry/rssfeeds/13352306.cms", 4),
    ("Economic Times - Startups", "https://economictimes.indiatimes.com/small-biz/startups/rssfeeds/11993050.cms", 4),
    ("Economic Times - Wealth", "https://economictimes.indiatimes.com/wealth/rssfeeds/837555174.cms", 3),
    ("ET CFO", "https://cfo.economictimes.indiatimes.com/rss/topstories", 3),
    ("ET BrandEquity", "https://brandequity.economictimes.indiatimes.com/rss/topstories", 3),
    ("afaqs", "https://www.afaqs.com/rss", 3),
    ("Inc42", "https://inc42.com/feed/", 3),
    ("YourStory", "https://yourstory.com/feed", 3),

    # Added 2026-09-21: technology, digital transformation, management and consulting. Every URL was
    # fetched and returned recent stories. Big 4, IT services and consulting firms mostly publish no feed of
    # their own, so they are covered through the Google News searches below.
    # Technology and digital transformation press
    ("Google News - Technology", "https://news.google.com/rss/topics/CAAqJggKIiBDQkFTRWdvSUwyMHZNRGRqTVhZU0FtVnVHZ0pWVXlnQVAB?hl=en-US&gl=US&ceid=US:en", 3),
    ("The Hindu - Technology", "https://www.thehindu.com/sci-tech/technology/feeder/default.rss", 4),
    ("Gadgets 360", "https://www.gadgets360.com/rss/news", 3),
    ("WSJ - Technology", "https://feeds.content.dowjones.io/public/rss/RSSWSJD", 5),
    ("Mashable - Tech", "https://mashable.com/feeds/rss/tech", 3),
    ("CNET", "https://www.cnet.com/rss/news/", 3),
    ("Indian Express - Technology", "https://indianexpress.com/section/technology/feed/", 4),
    ("ET CIO", "https://cio.economictimes.indiatimes.com/rss/topstories", 4),
    ("CX Today - Digital Transformation", "https://www.cxtoday.com/tag/digital-transformation/feed/", 3),
    ("ITPro", "https://www.itpro.com/feeds.xml", 4),
    ("Business Standard - Technology", "https://www.business-standard.com/rss/technology-108.rss", 4),
    ("CIO Dive", "https://www.ciodive.com/feeds/news/", 4),
    ("InformationWeek", "https://www.informationweek.com/rss.xml", 4),
    ("Computerworld", "https://www.computerworld.com/feed/", 4),
    ("InfoWorld", "https://www.infoworld.com/feed/", 4),
    ("TechRepublic", "https://www.techrepublic.com/rssfeeds/articles/", 3),
    ("The Register", "https://www.theregister.com/headlines.atom", 3),
    ("SiliconANGLE", "https://siliconangle.com/feed/", 3),
    ("Engadget", "https://www.engadget.com/rss.xml", 3),
    ("Diginomica", "https://diginomica.com/feed", 4),
    ("Enterprise Times", "https://www.enterprisetimes.co.uk/feed/", 3),
    ("Express Computer", "https://www.expresscomputer.in/feed/", 3),
    ("Analytics Vidhya", "https://www.analyticsvidhya.com/feed/", 3),
    ("Semafor Business", "https://www.semafor.com/rss.xml", 4),
    ("Rest of World", "https://restofworld.org/feed/", 4),
    ("Sifted", "https://sifted.eu/feed", 3),
    ("TechCabal", "https://techcabal.com/feed/", 3),
    ("MediaNama", "https://www.medianama.com/feed/", 4),
    # Management, strategy and consulting
    ("Capgemini", "https://www.capgemini.com/feed/", 4),
    ("Forrester Blogs", "https://www.forrester.com/blogs/feed", 4),
    ("Consultancy.uk", "https://www.consultancy.uk/rss/consultancy_rssfeed.xml", 3),
    ("Consultancy.in", "https://www.consultancy.in/rss/consultancy_rssfeed.xml", 3),
    ("HCLTech Blog", "https://www.hcltech.com/rss.xml", 4),
    ("Kellogg Insight", "https://insight.kellogg.northwestern.edu/feed/rss", 5),
    ("IIM Ahmedabad", "https://www.iima.ac.in/rss.xml", 3),
    ("Management Consulted", "https://managementconsulted.com/feed/", 3),
    ("Fast Company", "https://www.fastcompany.com/latest/rss", 4),
    ("Inc.", "https://www.inc.com/rss/", 3),
    ("Fortune", "https://fortune.com/feed/", 4),
    ("Quartz", "https://qz.com/rss", 3),
    ("Financial Times - Technology", "https://www.ft.com/technology?format=rss", 5),
    ("Bloomberg Technology", "https://feeds.bloomberg.com/technology/news.rss", 5),
    ("Business Insider", "https://www.businessinsider.com/rss", 3),
    # Company and vendor blogs
    ("SAP News Center", "https://news.sap.com/feed/", 4),
    ("Salesforce Blog", "https://www.salesforce.com/blog/feed/", 4),
    ("Microsoft Industry Blog", "https://www.microsoft.com/en-us/industry/blog/feed/", 4),
    ("Databricks Blog", "https://www.databricks.com/feed", 4),
    ("UiPath Blog", "https://www.uipath.com/blog/rss.xml", 3),
    ("Intercom Blog", "https://www.intercom.com/blog/feed/", 3),
    ("HubSpot Marketing Blog", "https://blog.hubspot.com/marketing/rss.xml", 4),
    ("Sequoia Capital", "https://www.sequoiacap.com/feed/", 4),
    ("SaaStr", "https://www.saastr.com/feed/", 3),
    ("Product Talk", "https://www.producttalk.org/feed/", 3),
    ("Farnam Street", "https://fs.blog/feed/", 3),
    ("Seth Godin", "https://seths.blog/feed/", 3),
    ("Benedict Evans", "https://www.ben-evans.com/benedictevans?format=rss", 4),
    ("Stratechery", "https://stratechery.com/feed/", 5),
    # India business, industry and technology
    ("Business Standard - Companies", "https://www.business-standard.com/rss/companies-101.rss", 4),
    ("Business Standard - Industry", "https://www.business-standard.com/rss/industry-217.rss", 4),
    ("BusinessLine - Info-tech", "https://www.thehindubusinessline.com/info-tech/feeder/default.rss", 4),
    ("The Hindu - Business", "https://www.thehindu.com/business/feeder/default.rss", 4),
    ("Indian Express - Business", "https://indianexpress.com/section/business/feed/", 4),
    ("Forbes India", "https://www.forbesindia.com/commonfeeds/v1/frb/rss/text.xml", 4),
    ("ThePrint - Economy", "https://theprint.in/category/economy/feed/", 3),
    ("ET Retail", "https://retail.economictimes.indiatimes.com/rss/topstories", 4),
    ("ET Telecom", "https://telecom.economictimes.indiatimes.com/rss/topstories", 4),
    ("ET BFSI", "https://bfsi.economictimes.indiatimes.com/rss/topstories", 4),
    ("ET Auto", "https://auto.economictimes.indiatimes.com/rss/topstories", 4),
    ("ET Government", "https://government.economictimes.indiatimes.com/rss/topstories", 4),
    # Google News searches (official RSS). Big 4, IT services and consulting firms publish no feed of their own
    ("Google News - Big 4", "https://news.google.com/rss/search?q=Deloitte+OR+PwC+OR+EY+OR+KPMG&hl=en-IN&gl=IN&ceid=IN:en", 3),
    ("Google News - McKinsey, BCG, Bain", "https://news.google.com/rss/search?q=McKinsey+OR+BCG+OR+%22Bain+%26+Company%22&hl=en-IN&gl=IN&ceid=IN:en", 3),
    ("Google News - Indian IT services", "https://news.google.com/rss/search?q=Infosys+OR+TCS+OR+Wipro+OR+HCLTech+OR+%22Tech+Mahindra%22&hl=en-IN&gl=IN&ceid=IN:en", 3),
    ("Google News - Accenture, Cognizant, Capgemini, IBM", "https://news.google.com/rss/search?q=Accenture+OR+Cognizant+OR+Capgemini+OR+IBM+Consulting&hl=en-IN&gl=IN&ceid=IN:en", 3),
    ("Google News - Digital transformation", "https://news.google.com/rss/search?q=%22digital+transformation%22&hl=en-IN&gl=IN&ceid=IN:en", 3),
    ("Google News - Consulting hiring", "https://news.google.com/rss/search?q=consulting+firms+hiring+OR+campus+placements+consulting&hl=en-IN&gl=IN&ceid=IN:en", 3),
    ("Google News - Enterprise AI", "https://news.google.com/rss/search?q=enterprise+AI+adoption+OR+%22generative+AI%22+enterprise&hl=en-IN&gl=IN&ceid=IN:en", 3),
    ("Google News - Management consulting", "https://news.google.com/rss/search?q=%22management+consulting%22&hl=en-IN&gl=IN&ceid=IN:en", 3),
    ("Google News - Technology (India)", "https://news.google.com/rss/headlines/section/topic/TECHNOLOGY?hl=en-IN&gl=IN&ceid=IN:en", 3),
    ("Google News - Business (India)", "https://news.google.com/rss/headlines/section/topic/BUSINESS?hl=en-IN&gl=IN&ceid=IN:en", 3),
    # Tech Brew and Morning Brew block automated feed readers with a Cloudflare challenge, so their
    # stories come through a Google News site: search instead of a direct feed.
    ("Google News - Tech Brew, Morning Brew", "https://news.google.com/rss/search?q=site:techbrew.com+OR+site:morningbrew.com&hl=en-US&gl=US&ceid=US:en", 4),
    ("Morning Brew Daily", "https://www.mbdailyshow.com/feed", 4),
]

# Newsletters, mostly on Substack, plus a few independent writers on other platforms. The app shows them in
# their own section, and they are ranked against a reader's profile like everything else.
NEWSLETTERS: list[tuple[str, str, int]] = [
    ("Lenny's Newsletter", "https://www.lennysnewsletter.com/feed", 4),
    ("Not Boring", "https://www.notboring.co/feed", 4),
    ("The Generalist", "https://www.generalist.com/feed", 4),
    ("The Pragmatic Engineer", "https://newsletter.pragmaticengineer.com/feed", 4),
    ("Platformer", "https://www.platformer.news/rss/", 4),
    ("Net Interest", "https://www.netinterest.co/feed", 4),
    ("Benn Stancil", "https://benn.substack.com/feed", 3),
    ("Ben's Bites", "https://www.bensbites.com/feed", 3),
    ("One Useful Thing", "https://www.oneusefulthing.org/feed", 4),
    ("Import AI", "https://importai.substack.com/feed", 3),
    ("Exponential View", "https://www.exponentialview.co/feed", 4),
    ("Digital Native", "https://www.digitalnative.tech/feed", 3),
    ("Product Growth", "https://www.news.aakashg.com/feed", 3),
    ("The Daily Brief (Zerodha)", "https://thedailybrief.zerodha.com/feed", 4),
    ("Finshots", "https://finshots.in/rss/", 4),
    ("Noahpinion", "https://www.noahpinion.blog/feed", 3),
    ("Tomasz Tunguz", "https://tomtunguz.com/index.xml", 3),
    ("Refactoring", "https://refactoring.fm/feed", 3),
    ("Tech Buzz China", "https://techbuzzchina.substack.com/feed", 3),
    ("Newcomer", "https://www.newcomer.co/feed", 3),
    ("Puck", "https://puck.news/feed/", 4),
    ("The Information", "https://www.theinformation.com/feed", 5),
    ("The Looking Glass", "https://lg.substack.com/feed", 3),
    ("Shreyas Doshi", "https://shreyasdoshi.substack.com/feed", 3),
    ("The Playbook (Morning Brew)", "https://www.theplaybookmb.com/feed.xml", 4),
    ("So, What's the Big News?", "https://shailendrabisht.substack.com/feed", 3),
]
NEWSLETTER_NAMES = frozenset(name for name, _, _ in NEWSLETTERS)
SOURCES += NEWSLETTERS

SAMPLE_SOURCE = ("Vantage Samples (placeholder)", "vantage://samples", 1)
